apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "odoo.fullname" . }}-worker
  labels:
    {{- include "odoo.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "odoo.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "odoo.labels" . | nindent 8 }}
        app.kubernetes.io/component: worker
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.odooinit.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "odoo.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: "{{ .Chart.Name }}-worker"
          {{- if .Values.odooinit.restore.enabled }}
          env:
            - name: ODOO_WAIT_FOR_RESTORE
              value: "1"
          {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.odooinit.image.repository }}:{{ .Values.odooinit.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.odooinit.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            - name: http-websocket
              containerPort: {{ .Values.service.websocketPort }}
              protocol: TCP
          {{- if .Values.startupProbe.enabled }}
          startupProbe:
            httpGet:
              path: {{ .Values.startupProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.startupProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.startupProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.startupProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.startupProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: {{ include "odoo.fullname" . }}-config-vol
              mountPath: /data/etc
              readOnly: true
            - name: {{ include "odoo.fullname" . }}-session-vol
              mountPath: /data/sessions
            - name: {{ include "odoo.fullname" . }}-filestore-vol
              mountPath: /data/filestore
            {{- if .Values.odooinit.backup.volumeClaim }}
            - name: {{ include "odoo.fullname" . }}-backup-vol
              mountPath: /data/backup
            {{- end }}
            {{- with .Values.volumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          envFrom:
            - secretRef:
                name: "{{ include "odoo.fullname" . }}-postgres-config"
      volumes:
        - name: {{ include "odoo.fullname" . }}-config-vol
          secret:
            secretName: {{ include "odoo.fullname" . }}-config
        - name: {{ include "odoo.fullname" . }}-session-vol
          persistentVolumeClaim:
            claimName: {{ include "odoo.fullname" . }}-sessionstore
        - name: {{ include "odoo.fullname" . }}-filestore-vol
          persistentVolumeClaim:
            claimName: {{ include "odoo.fullname" . }}-filestore
        {{- if .Values.odooinit.backup.volumeClaim }}
        - name: {{ include "odoo.fullname" . }}-backup-vol
          persistentVolumeClaim:
            claimName: {{ .Values.odooinit.backup.volumeClaim }}
        {{- end }}
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
