{{- if and (gt (int .Values.odooinit.workers) 0) (gt (int .Values.odooinit.cronThreads) 0) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "odoo.fullname" . }}-cron
  labels:
    {{- include "odoo.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ min .Values.replicaCount .Values.maxCronReplicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "odoo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "odoo.labels" . | nindent 8 }}
	{{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.odooinit.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "odoo.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: "{{ .Chart.Name }}-cron"
          env:
            - name: ODOO_CONFIG
              value: "/data/etc/odoo-cron.conf"
            - name: ODOO_WAIT_FOR_RESTORE
              value: "1"
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.odooinit.image.repository }}:{{ .Values.odooinit.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.odooinit.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: {{ include "odoo.fullname" . }}-config-vol
              mountPath: /data/etc
              readOnly: true
            - name: {{ include "odoo.fullname" . }}-session-vol
              mountPath: /data/sessions
            - name: {{ include "odoo.fullname" . }}-filestore-vol
              mountPath: /data/filestore
            {{- if .Values.odooinit.backup.volumeClaim }}
            - name: {{ include "odoo.fullname" . }}-backup-vol
              mountPath: /data/backup
            {{- end }}
            {{- with .Values.volumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          envFrom:
            - secretRef:
                name: "{{ include "odoo.fullname" . }}-postgres-config"
      volumes:
        - name: {{ include "odoo.fullname" . }}-config-vol
          secret:
            secretName: {{ include "odoo.fullname" . }}-config
        - name: {{ include "odoo.fullname" . }}-session-vol
          persistentVolumeClaim:
            claimName: {{ include "odoo.fullname" . }}-sessionstore
        - name: {{ include "odoo.fullname" . }}-filestore-vol
          persistentVolumeClaim:
            claimName: {{ include "odoo.fullname" . }}-filestore
        {{- if .Values.odooinit.backup.volumeClaim }}
        - name: {{ include "odoo.fullname" . }}-backup-vol
          persistentVolumeClaim:
            claimName: {{ .Values.odooinit.backup.volumeClaim }}
        {{- end }}
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}