{{- if .Values.argocd.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "odoo.fullname" . }}-worker
  labels:
    {{- include "odoo.labels" . | nindent 4 }}
  annotations:
    "argocd.argoproj.io/sync-wave": "-23"
spec:
  replicas: 0
{{- end }}