{{- if .Values.ingress.enabled -}}
{{- $fullName := include "odoo.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- $svcWebsocketPort := .Values.service.websocketPort -}}
{{- $tlsSecretName := include "odoo.ingress.tlsSecretName" . -}}
{{- $workers := .Values.odooinit.workers -}}
{{- if and .Values.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingress.annotations "kubernetes.io/ingress.class" .Values.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "odoo.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if eq .Values.ingress.className "nginx" }}
    nginx.org/client-max-body-size: "{{ .Values.ingress.maxBodySize }}"
    nginx.ingress.kubernetes.io/proxy-body-size: "{{ .Values.ingress.maxBodySize }}"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "{{ .Values.ingress.timeout }}"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "{{ .Values.ingress.timeout }}"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "{{ .Values.ingress.timeout }}"
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "{{ .Values.ingress.proxyBuffer }}"
    nginx.ingress.kubernetes.io/proxy-max-temp-file-size: "{{ .Values.ingress.maxBodySize }}"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      {{- if .Values.ingress.cloudflare }}
      proxy_set_header X-Real-IP $http_true_client_ip;
      proxy_set_header X-Forwarded-For $http_cf_connecting_ip;
      {{- end }}
    {{- end }}
spec:
  {{- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if  $tlsSecretName }}
  tls:
    - hosts:
        {{- range .Values.hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{  $tlsSecretName }}
  {{- end }}
  {{- with .Values.ingress.defaultBackend }}
  defaultBackend:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
    {{- end }}
---
{{- if $workers }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-longpolling
  labels:
    {{- include "odoo.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if eq .Values.ingress.className "nginx" }}
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "{{ .Values.ingress.timeout }}"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "{{ .Values.ingress.timeout }}"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "{{ .Values.ingress.timeout }}"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      {{- if .Values.ingress.cloudflare }}
      proxy_set_header X-Real-IP $http_true_client_ip;
      proxy_set_header X-Forwarded-For $http_cf_connecting_ip;
      {{- end }}
    {{- end }}
spec:
  {{- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if  $tlsSecretName }}
  tls:
    - hosts:
        {{- range .Values.hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{  $tlsSecretName }}
  {{- end }}
  rules:
    {{- range .Values.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: /websocket
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcWebsocketPort  }}
    {{- end }}
{{- end }}
{{- end }}