
{{- if and .Values.ingressroute.enabled (eq .Values.ingressroute.className "traefik") }}
{{- $fullName := include "odoo.fullname" . -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "odoo.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingressroute.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  entryPoints:
    - websecure
  routes:
  {{- range .Values.hosts }}
    - match: Host(`{{ . }}`) && PathPrefix(`/websocket`)
      kind: Rule
      services:
        - name: {{ $fullName }}
          port: 8072
    - match: Host(`{{ . }}`)
      kind: Rule
      services:
        - name: {{ $fullName }}
          port: 8069
  {{- end }}
  {{- $tlsSecretName := include "odoo.ingressroute.tlsSecretName" . }}
  {{- if $tlsSecretName }}
  tls:
    secretName: {{ $tlsSecretName }}
  {{- end }}
{{- end }}