{{- if .Values.argocd.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "odoo.fullname" . }}-scale-down
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "argocd.argoproj.io/hook": PreSync
    "argocd.argoproj.io/hook-delete-policy": BeforeHookCreation
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: Never
      serviceAccountName: argocd-application-controller
      containers:
        - name: {{ include "odoo.fullname" . }}-scale-down
          image: "bitnami/kubectl:latest"
          command: ["/bin/sh","-c", "kubectl scale deployment {{ include "odoo.fullname" . }}-worker --replicas=0"]
          resources:
            limits:
              memory: "1Gi"
              cpu: "1"
            requests:
              cpu: "100m"
              memory: "100Mi"
{{- end }}
