{{- if and .Values.backup.enabled (not .Values.setup) -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "odoo.fullname" . }}-backup
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-11"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "odoo.fullname" . }}-backup
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          args:
          - backup
          - "--backup-dir={{ .Values.backup.path }}"
          - "--backlog={{ .Values.backup.backlog }}"
          - "--only-database"
          {{- if .Values.backup.compress }}
          - "--compress"
          {{- end }}
          volumeMounts:
            - name: {{ include "odoo.fullname" . }}-config-vol
              mountPath: /data/etc
              readOnly: true
            {{- if not .Values.sessionstore.db }}
            - name: {{ include "odoo.fullname" . }}-session-vol
              mountPath: /data/sessions
            {{- end }}
            - name: {{ include "odoo.fullname" . }}-filestore-vol
              mountPath: /data/filestore
            {{- if .Values.backup.volumeClaim }}
            - name: {{ include "odoo.fullname" . }}-backup-vol
              mountPath: /data/backup
            {{- end }}
            {{- with .Values.volumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          envFrom:
            - secretRef:
                name: "{{ include "odoo.fullname" . }}-postgres-config"
            - secretRef:
                name: "{{ include "odoo.fullname" . }}-postgres-admin-config"
      volumes:
        - name: {{ include "odoo.fullname" . }}-config-vol
          secret:
            secretName: {{ include "odoo.fullname" . }}-config
        {{- if not .Values.sessionstore.db }}
        - name: {{ include "odoo.fullname" . }}-session-vol
          persistentVolumeClaim:
            claimName: {{ include "odoo.fullname" . }}-sessionstore
        {{- end }}
        - name: {{ include "odoo.fullname" . }}-filestore-vol
          persistentVolumeClaim:
            claimName: {{ include "odoo.fullname" . }}-filestore
        {{- if .Values.backup.volumeClaim }}
        - name: {{ include "odoo.fullname" . }}-backup-vol
          persistentVolumeClaim:
            claimName: {{ .Values.backup.volumeClaim }}
        {{- end }}
        {{- with .Values.volumes }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
{{- end }}